--- 
title: "Computational Statistics with R"
author: "Niels Richard Hansen"
date: "`r paste(Sys.Date(), ', Git version: ', system('git rev-parse --short HEAD', intern = TRUE), sep = '')`"
output:
  pdf_document: default
  html_document:
    df_print: paged
description: Lecture notes providing an introduction to computational statistics using
  the R programming language.
documentclass: book
papersize: a4
fontsize: 11pt
link-citations: yes
bibliography: CSwR.bib
site: bookdown::bookdown_site
biblio-style: apalike
---

# Preface {-}

This is draft material for a book on computational statistics, which is being 
developed specifically for the master's education in statistics at
University of Copenhagen. 

A solid mathematical background is assumed throughout, while the 
computer science prerequisites are more modest. To be specific, the reader
is expected to have a reasonable command of mathematical analysis, linear 
algebra and mathematical statistics, as exemplified by maximum likelihood estimation 
of multivariate parameters and asymptotic properties of such a multivariate
estimator. The reader is expected to have an understanding of what 
an algorithm is, how numerical computations differ from symbolic computations, 
and be able to write small computer programs. 

The intention of the material is to serve as a pedagogical introduction to 
computational statistics. No claim is made that the material is
comprehensive or even representative, nor does it purport computational 
statistics as a single coherent field with a unifying theoretical foundation.
This introduction is driven by statistical examples with the unifying theme 
being an experimental approach to solving computational problems in statistics.

Contemporary challenges in computational statistics revolve around 
large scale computations, either because the amount of data is massive or 
because we want to apply ever more complicated and sophisticated models 
and methods for the analysis and visualization of data. The examples treated
are all of a rather modest complexity compared to these 
challenges. This is deliberate! A solid understanding of how to solve 
simpler problems is a prerequisite for solving complex problems. It is 
the hope that this material provides the reader 
with a foundation in computational statistics that will subseqently make 
him or her able to attack and solve novel problems in 
computational statistics.

