version: "3"

tasks:
  render-pdf-book:
    desc: Render the PDF book
    cmds:
      - Rscript -e "bookdown::render_book('index.Rmd', output_format = 'bookdown::pdf_book')"

  render-html-book:
    desc: Render the HTML book
    cmds:
      - Rscript -e "bookdown::render_book('index.Rmd', output_format = 'bookdown::bs4_book')"

  serve-html-book:
    desc: Serve the HTML book
    cmds:
      - Rscript -e "bookdown::serve_book('index.Rmd')"
