name: Render Bookdown Site

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v17
        with:
          name: jolars
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv

      - name: Restore timestamps
        uses: chetan/git-restore-mtime-action@v2

      - name: Cache bookdown results
        uses: actions/cache@v5
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Render book
        run: devenv shell Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::bs4_book")'
        env:
          CHROMOTE_CHROME: chromium
          RENV_CONFIG_AUTOLOADER_ENABLED: "false"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: _book
